name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend_ip: ${{ steps.get_ip.outputs.backend_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest

      - name: Deploy to Azure Container Instance
        id: deploy_backend
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name backend-service \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest \
            --ports 8000 \
            --restart-policy Always \
            --dns-name-label backend-${{ github.run_number }}
      
      - name: Get backend IP
        id: get_ip
        run: |
          BACKEND_IP=$(az container show \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name backend-service \
            --query "ipAddress.ip" -o tsv)
          echo "backend_ip=$BACKEND_IP" >> $GITHUB_OUTPUT
