name: Frontend CD

on:
  workflow_call:
    inputs:
      backend_ip:
        required: true
        type: string

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Replace backend API URL in frontend
        run: |
          sed -i "s|http://localhost:8000|http://${{ inputs.backend_ip }}:8000|g" ./frontend/src/config.js

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name frontend-service \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest \
            --ports 80 \
            --restart-policy Always \
            --dns-name-label frontend-${{ github.run_number }}
